<a href="https://colab.research.google.com/github/DhairyaDave08/Machine-Learning/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Algebra
* Vector Operation
* Matrix Operation
* Eigen value and Eigen Vector
* SVD
* Low Rank Approximation




In [ ]:
import numpy as np

##Vector Declaration

In [ ]:
a=np.array([1,0,0])
b=np.array([0,1,0])

##Vector Operations


In [ ]:
print("vector A: ",a)
print("vector B: ",b)

print("Sum of vectors: ",a+b)
print("Diff of vectors: ",a-b)

d=np.dot(a,b)
print("Dot Product: ",d)

s1=np.linalg.norm(a)
print("Magnitude of vector A: ",s1)
s2=np.linalg.norm(b)
print("Magnitude of vector B: ",s2)

theta=np.arccos(d/(s1*s2))
print("Angle between vectors: ",np.degrees(theta))

vector A:  [1 0 0]
vector B:  [0 1 0]
Sum of vectors:  [1 1 0]
Diff of vectors:  [ 1 -1  0]
Dot Product:  0
Magnitude of vector A:  1.0
Magnitude of vector B:  1.0
Angle between vectors:  90.0


## Matrix Declarations

In [ ]:
x=np.array([[1,0,0],[0,0,0],[0,0,1]])
y=np.array([[0,0,0],[0,1,0],[0,0,0]])

##Matrix Operations

In [ ]:
d=x+y
print("Matrix D: ",d)
print("Matrix D transpose: ",d.T)

dete=np.linalg.det(d)
print("Determinant: ",dete)


matmul=np.dot(x,y)
print("Matrix multiplication: ",matmul)


invq=np.linalg.inv(d)
print("Inverse: ",invq)

shape=np.shape(d)
print("Shape: ",shape)


Matrix D:  [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix D transpose:  [[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinant:  1.0
Matrix multiplication:  [[0 0 0]
 [0 0 0]
 [0 0 0]]
Inverse:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)


##Gram Schmidt Orthogonalisation

In [ ]:
A = np.array([
    [2, 0],
    [0, 0],
    [0, 2]
], dtype=float)
a1 = A[:, 0]
q1 = a1 / np.linalg.norm(a1)
a2 = A[:, 1]
proj = np.dot(a2, q1) * q1
u2 = a2 - proj
q2 = u2 / np.linalg.norm(u2)
Q = np.column_stack((q1, q2))

print("Q matrix:")
print(Q)

Q matrix:
[[1. 0.]
 [0. 0.]
 [0. 1.]]


## Eigenvalues and EigenVectors


In [ ]:
z=np.array([[2,-2,3],[1,1,1],[1,3,-1]])
eigenval,eigenvec=np.linalg.eig(z)
print("EigenValues: ",eigenval)
print("Eigenvector: ",eigenvec)
print("Determinant:" ,np.linalg.det(z))

EigenValues:  [ 3.  1. -2.]
Eigenvector:  [[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]
Determinant: -6.0


##Singular Value Decomposition



In [ ]:
np.set_printoptions(precision=4,suppress=True)

In [ ]:
p=np.array([[1,2,3,-1,2],[0,1,3,2,-1],[1,1,-2,0,1],[2,1,3,-1,0]])
u,s,v=np.linalg.svd(p,full_matrices=True)
#u,s,v=np.linalg.svd(p,full_matrices=False) -> it will reduce matrix size
print("U: \n",u)
print("S: \n",s)
print("V: \n",v)
print("\n")
print(np.shape(u))
print(np.shape(v.T))
sd=np.zeros((4,5))
sd[:,:4]=np.diag(s)
print("\nMatrix Multiplication of u and u transpose:\n",np.dot(u,u.T))

U: 
 [[ 0.6398  0.4763 -0.1462 -0.5852]
 [ 0.4602 -0.6795 -0.5641  0.091 ]
 [-0.1711  0.5323 -0.7124  0.4241]
 [ 0.5913  0.1676  0.391   0.6851]]
S: 
 [6.1026 3.5806 1.9211 1.4989]
V: 
 [[ 0.2706  0.3539  0.8875 -0.0509  0.1062]
 [ 0.3753  0.2717 -0.3272 -0.5594  0.6045]
 [-0.0398 -0.6131  0.2431 -0.7147 -0.2294]
 [ 0.8067  0.0199 -0.1839  0.0548 -0.5586]
 [ 0.3655 -0.6516  0.1113  0.4132  0.5086]]


(4, 4)
(5, 5)

Matrix Multiplication of u and u transpose:
 [[ 1.  0. -0.  0.]
 [ 0.  1.  0. -0.]
 [-0.  0.  1.  0.]
 [ 0. -0.  0.  1.]]


##Low Rank Approximation

In [ ]:
c = 3
sdp = np.zeros((c, c))
sdp[:, :c] = sd[:c, :c]
pp=np.dot(u[:,:c],np.dot(sdp,v[:c,:]))
print("Low Rank Approximation: \n",pp)
print("Og matrix: \n",p)

Low Rank Approximation: 
 [[ 1.7076  2.0174  2.8387 -0.952   1.51  ]
 [-0.11    0.9973  3.0251  1.9925 -0.9238]
 [ 0.4872  0.9874 -1.8831 -0.0348  1.3551]
 [ 1.1716  0.9796  3.1888 -1.0562  0.5736]]
Og matrix: 
 [[ 1  2  3 -1  2]
 [ 0  1  3  2 -1]
 [ 1  1 -2  0  1]
 [ 2  1  3 -1  0]]
